### ISSUE TITLE
Welcome dialog displays connections implemented differently than in the tool

### ISSUE THREAD

**Issue by mmanciop** [dash0hq/otelbin#155] opened 2023-10-30 16:06 UTC
The support for connectors as [displayed in the welcome dialog](https://github.com/dash0hq/otelbin/blob/main/packages/otelbin/src/components/assets/png/welcome-modal-slide-4.png) displays linking the matching exporters and receivers in pipelines, but that is not implemented in the tool. The welcome image should be updated to reflect that.

**Comment by bripkens** [comment] 2023-10-30 16:07
Depends on us getting the updated marketing images that we also want to use for ProductHunt. Duplicate of https://github.com/dash0hq/otelbin/issues/92

**Closed by bripkens** 2023-10-30 16:07 UTC
Labels: bug
